apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: auth-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JWT_SECRET
          value: "PRFT"
        - name: AUTH_API_PORT
          value: "8081"
        - name: USERS_API_ADDRESS
          value: "http://users-api:8083"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
  - port: 8081
    targetPort: 8081
