version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  auth-api:
    build:
      context: ../auth-api
      dockerfile: ../dockerfiles/dockerfile.authApi
    container_name: auth-api
    environment:
      - JWT_SECRET=PRFT
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=http://users-api:8083
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - users-api
    networks:
      - backend

  todos-api:
    build:
      context: ../todos-api
      dockerfile: ../dockerfiles/dockerfile.todoApi
    container_name: todos-api
    environment:
      - JWT_SECRET=PRFT
      - TODO_API_PORT=8082
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - auth-api
    networks:
      - backend

  users-api:
    build:
      context: ../users-api
      dockerfile: ../dockerfiles/dockerfile.userApi
    container_name: users-api
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=PRFT
    ports:
      - "8083:8083"
    networks:
      - backend

  log-processor:
    build:
      context: ../log-message-processor
      dockerfile: ../dockerfiles/dockerfile.log-message
    container_name: log-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    networks:
      - backend

  frontend:
    build:
      context: ../frontend
      dockerfile: ../dockerfiles/dockerfile.frontend
    container_name: frontend
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8081
      - TODOS_API_ADDRESS=http://todos-api:8082
    ports:
      - "8080:8080"
    depends_on:
      - auth-api
      - todos-api
    networks:
      - backend

networks:
  backend:
    driver: bridge
