# Imagen base de Node
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /usr/src/app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install --production

# Copiar el resto del código
COPY . .

# Variables por defecto
ENV TODO_API_PORT=8082
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
ENV REDIS_CHANNEL=todos_channel
ENV JWT_SECRET=PRFT

# Exponer el puerto
EXPOSE 8082

# Comando por defecto
CMD ["npm", "start"]
