FROM python:3.9-slim

WORKDIR /app

# Copiar archivos del microservicio
COPY . .

# Instalar dependencias
RUN pip3 install --no-cache-dir -r requirements.txt

# Variables de entorno por defecto
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
ENV REDIS_CHANNEL=log_channel

CMD ["python3", "main.py"]
