apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: users-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_PORT
          value: "8083"
        - name: JWT_SECRET
          value: "PRFT"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  type: ClusterIP
  selector:
    app: users-api
  ports:
  - port: 8083
    targetPort: 8083
